---
apiVersion: v1
kind: Namespace
metadata:
  name: alice
---
apiVersion: v1
kind: Namespace
metadata:
  name: bob
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alice-dashboard
  namespace: kube-dashboard
  annotations:
    user: alice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob-dashboard
  namespace: kube-dashboard
  annotations:
    user: bob

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alice-dashboard
  namespace: alice
subjects:
- kind: ServiceAccount
  name: alice-dashboard
  namespace: kube-dashboard
roleRef:
  kind: ClusterRole 
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bob-dashboard
  namespace: bob
subjects:
- kind: ServiceAccount
  name: bob-dashboard
  namespace: kube-dashboard
roleRef:
  kind: ClusterRole 
  name: admin
  apiGroup: rbac.authorization.k8s.io
---